### ISSUE TITLE
Avatars aren't working

### ISSUE THREAD

**Issue by Ismoh** [NBprojekt/gource-action#13]
Here you can see my workflow action yaml:
```yaml
name: Gource
on:
  push:
    branches:
      - '**'

jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          avatars_auto_fetch: true
          gource_title: 'NoitaMP Gource master'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          gource_auto_skip_seconds: 0.1
          gource_seconds_per_day: 0.1

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4
```
https://github.com/Ismoh/NoitaMP/blob/69-integrate-gourceio-because-its-fun/.github/workflows/gource.yml#L20

As you can see in the action result, there aren't any avatars shown:
https://github.com/Ismoh/NoitaMP/actions/runs/2962234230
![image](https://user-images.githubusercontent.com/12631485/187691633-575f48f3-af67-45ac-94e0-4b41f6c2847d.png)

Only the artifact:
https://github.com/Ismoh/NoitaMP/suites/8064812629/artifacts/347452077
