### ISSUE TITLE
Add support for --file-filter

### ISSUE THREAD

**Issue by koppor** [NBprojekt/gource-action#5]
How to apply `--file-filter`? (source: https://github.com/acaudwell/Gource/blob/master/README) `gource_file_filter` doesn't seem to be a valid option:

![grafik](https://user-images.githubusercontent.com/1366654/109567592-e6032f80-7ae5-11eb-846f-aa7ff7ffdeac.png)

I try to run with

```yaml
      - name: 'Complete development history'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'JabRef | more information at contribute.jabref.org'
          logo_url: 'https://www.jabref.org/img/JabRef-icon-256.png'
          gource_seconds_per_day: 0.1
          gource_file_filter: csl$
```

(PR: https://github.com/JabRef/jabref/pull/7193)
