### ISSUE TITLE
Autofetch contributors avatars

### ISSUE THREAD

**Issue by NBprojekt** [NBprojekt/gource-action#6]
Create a functions that optionaly fetches all contributor avatars and downloads them into the avatars directory.

**Comment by Ismoh** [comment]
I could use some help with avatars.

```yaml
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          avatars_auto_fetch: true
          gource_title: 'NoitaMP Gource master'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          gource_auto_skip_seconds: 0.1
          gource_seconds_per_day: 0.1
```
![image](https://user-images.githubusercontent.com/12631485/187629453-7bfb7aca-6ba1-4298-aca3-32337ad7c67e.png)

Looks like `avatars_auto_fetch: true` isn't working, because I am not able to see any avatars.
How can I fix this?
